### ISSUE TITLE
i cant play some people in chess.com

### ISSUE THREAD

**Issue by jonnyop123** [Auzgame/userscripts#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Logs from your browser's developer tools console.

**Desktop (please complete the following information):**

**Additional context**

**Comment by Auzgame** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Logs** Logs from your browser's developer tools console.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Please fill in the template

**Comment by Auzgame** [comment]
Closed due to inactivity
