### ISSUE TITLE
Cant even beat the queen archer

### ISSUE THREAD

**Issue by idkidk29183** [Auzgame/userscripts#12]
I tried to play vs. the queen archer, which is at 2900 elo like 4 times using this script, which claims it uses stockfish, the world's #1 chess engine and somehow it lost. I don't think this hack/cheat could even bet a 2500 elo rated player.

**Comment by Auzgame** [comment]
> I tried to play vs. the queen archer, which is at 2900 elo like 4 times using this script, which claims it uses stockfish, the world's #1 chess engine and somehow it lost. I don't think this hack/cheat could even bet a 2500 elo rated player.

What depth were you playing on?

**Comment by idkidk29183** [comment]
11

**Comment by Auzgame** [comment]
> 11

Then use a higher depth.

**Comment by Dface1221** [comment]
hey how i can change the depth my current depth is 11 and i want to change it to 4 any way to change yesterday i don't know but my depth was somehow 4 and i don't know how i can do again

**Comment by Auzgame** [comment]
> hey how i can change the depth my current depth is 11 and i want to change it to 4 any way to change yesterday i don't know but my depth was somehow 4 and i don't know how i can do again

Quote from the info page on the download page: "Each letter on the standard qwerty keyboard represents a different depth. For instance, q represent 1 and m represents 26"

**Comment by Auzgame** [comment]
Closed due to inactivity
