### ISSUE TITLE
How to make it move more faster

### ISSUE THREAD

**Issue by jameslope** [Auzgame/userscripts#15]
Hi sir when i use it. It is not the same speed on chess com i only use 2 depth. Sir when I am using a chess com script from you I go to line 634 and 637 var currentDelay = myVars.delay != undefined ? myVars.delay * 1000 : 10;
            other(currentDelay);
        }
    }, 100);
 I change this sir 100 to 0 and it become more faster to move and sometimes it look like it's premoving, what line sir do I need to find this? or can you add this sir to lichess script

**Comment by Auzgame** [comment]
> Hi sir when i use it. It is not the same speed on chess com i only use 2 depth. Sir when I am using a chess com script from you I go to line 634 and 637 var currentDelay = myVars.delay != undefined ? myVars.delay * 1000 : 10;
> 
>             other(currentDelay);
> 
>         }
> 
>     }, 100);
> 
>  I change this sir 100 to 0 and it become more faster to move and sometimes it look like it's premoving, what line sir do I need to find this? or can you add this sir to lichess script 

That line of code has to do with waiting before moving witch isn't active unless u check the box. Changing anything here wouldn't make the bit faster at all. The lichess bot doesn't have a delay function yet until I add it.

**Comment by jameslope** [comment]
I'm going to wait sir until you add it btw thanks sir it is really great
script

**Comment by jameslope** [comment]
I'm going to wait sir until you add it btw thanks sir it is really great script
