### ISSUE TITLE
random time

### ISSUE THREAD

**Issue by HaiTechie** [Auzgame/userscripts#16]
can random time move precise. for exam 1.5-2.5, the bot only recognize it as 1-2.

**Comment by Auzgame** [comment]
Is this for LiChess or Chess.com?

**Comment by Auzgame** [comment]
> can random time move precise. for exam 1.5-2.5, the bot only recognize it as 1-2.

After the time passes, the bot begins processing the best move to make, which this is the part that can take some time to complete adding on to the delay. I do plan on optimizing this at some point by adding pondering

**Comment by HaiTechie** [comment]
and if i want to play depth 7. i press A to auto move. it will change the depth to 11.

**Comment by Auzgame** [comment]
The QWERTY keyboard represents different strengths A corresponds to 11 and for a strength of 7 you'd use the 7th key being u

**Comment by jameslope** [comment]
> can random time move precise. for exam 1.5-2.5, the bot only recognize it as 1-2.

Bro if your move always 2.5 or 1.5 chess com will detect that and ban you immediately. To be honest this random time is very good it will think sometimes and move faster and make premove. If cheat on chess com this is the best

**Comment by HaiTechie** [comment]
i mean. if i setup de lay 1-2 or 1.9-2.9 . the bot only took it as 1-2. in bullet you cant setup slower. and every microsec setup  matter

**Comment by changsweet** [comment]
> The QWERTY keyboard represents different strengths A corresponds to 11 and for a strength of 7 you'd use the 7th key being u

so how can i auto move without changing it. thats the point

**Comment by Auzgame** [comment]
> i mean. if i setup de lay 1-2 or 1.9-2.9 . the bot only took it as 1-2. in bullet you cant setup slower. and every microsec setup matter

If u set it as 1-2 and it goes after 1-2 that means its working as intended. no?

**Comment by HaiTechie** [comment]
broooooooooooooo. if i setup 1.9-2.9. the bot still move around 1-2. why so hard to understand

**Comment by HaiTechie** [comment]
should count one more decimal

**Comment by Auzgame** [comment]
Might just be browser dependent. Idk, the minimum allowed value is 0.1. If no value is present the bot runs at 10 ms or .01 second delays

**Comment by changsweet** [comment]
![image](https://github.com/Auzgame/userscripts/assets/29919095/fe93e7fc-b36d-4793-b395-4882b94828a7)
look at this. i setup 1.9-2.9 but it only move around 1-2. it rouned 1.9 to 1 and 2.9 to 2.

**Comment by HaiTechie** [comment]
its ok bro. i changed ParseInt to ParseFloat.

**Comment by Auzgame** [comment]
Yeah, that makes sense now I'll probably change that in the next update. Thank you for this.
