### ISSUE TITLE
Getting banned too early 

### ISSUE THREAD

**Issue by realpritam** [Auzgame/userscripts#19]
Iam getting banned after 3-4 matches any way to fix it

**Comment by Auzgame** [comment]
> Iam getting banned after 3-4 matches any way to fix it

Unfortunately I can't magically unban someone. However, I can give you some pointers on how not to get banned.
1) Use the min and max delay settings
2) If you are using them, set the delays to a reasonable amount of time and spread out the min and max
3) You should play a couple turns here and there to launder your turns
