### ISSUE TITLE
Auto Move feature does not work properly

### ISSUE THREAD

**Issue by FatMidget** [Auzgame/userscripts#2]
Every move it makes, i have to reload it for it to make another move

**Comment by naradashen** [comment]
> Every move it makes, i have to reload it for it to make another move

Its because chess.com recognizes that you are using a bot and redirect you to another page

**Comment by Auzgame** [comment]
> Every move it makes, i have to reload it for it to make another move

Going off what @naradashen, you can either play with the settings or try a different browser. 
Also, could I get some additional information such as:
1) OS [Windows, Mac, etc.]
2) Browser
3) Logs from the developer tool console.

**Comment by Auzgame** [comment]
Closed due to inactivity

**Comment by Mon2903aZ** [comment]
sometimes it doesn't automatically switch anymore, i have to hit reload again to keep it going
