### ISSUE TITLE
so my cheat wont work on lichess.org

### ISSUE THREAD

**Issue by nullxs** [Auzgame/userscripts#22]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Logs from your browser's developer tools console.

**Desktop (please complete the following information):**

**Additional context**

**Comment by Auzgame** [comment]
Im sorry but the above is not filled out. I can't help you unless you fill it out

**Comment by nullxs** [comment]
To Reproduce
Steps to reproduce the behavior:

Go to '[...](https://lichess.org/'
Click on 'auto run'
Scroll down to 'reload chess engine'
See error

Expected behavior
i expected for the thing to start like how chess.com did
Logs
FEN: 1nbq2nr/1pp1b1k1/3RPp1p/1B4N1/7B/6Q1/rpP2PPP/1N2K2R
userscript.html?name…7-a8052d070836:9473 FEN: 1nbq2nr/1pp1b1k1/4Pp1p/1B4N1/7B/6Q1/rpPR1PPP/1N2K2R
userscript.html?name…7-a8052d070836:9484 Recieved Reply
userscript.html?name…7-a8052d070836:9473 FEN: rnbq2nr/1pp1b1k1/4Pp1p/1B4N1/7B/6Q1/1pPR1PPP/1N2K2R
userscript.html?name…7-a8052d070836:9473 FEN: rnbq2nr/1pp1b1k1/4Pp1p/1B6/4N2B/6Q1/1pPR1PPP/1N2K2R
userscript.html?name…7-a8052d070836:9484 Recieved Reply
userscript.html?name…7-a8052d070836:9473 FEN: rnbq1knr/1pp1b3/4Pp1p/1B6/4N2B/6Q1/1pPR1PPP/1N2K2R
userscript.html?name…7-a8052d070836:9473 FEN: rnbq1knr/1pp1b3/4PB1p/1B6/4N3/6Q1/1pPR1PPP/1N2K2R
userscript.html?name…7-a8052d070836:9484 Recieved Reply
﻿

Desktop (please complete the following information):

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]

**Comment by Auzgame** [comment]
Fixed in Latest Version.
Thankyou for bringing this to my attention.
