### ISSUE TITLE
Cant delete it from my ches.com website

### ISSUE THREAD

**Issue by Kinghh159** [Auzgame/userscripts#3]
I tried everything to delete it from chess.com and theres no button or how to do it please help

**Comment by Kinghh159** [comment]
now i cant play normal battles on my pc

**Comment by Auzgame** [comment]
So what your saying is, you don't know how to use tampermonkey and remove scripts?

[How to remove script from tampermonkey](https://www.wikihow.com/Delete-a-Script-in-Tampermonkey#:~:text=Navigate%20to%20the%20script%20which,icon%2C%20near%20your%20script's%20name.&text=Confirm%20your%20action.,the%20script%20from%20your%20system.)
