### ISSUE TITLE
Improvemement on chess cheating script

### ISSUE THREAD

**Issue by Anonymous140041** [Auzgame/userscripts#4]
Just suggesting you could allow the users to adjust the strength of the bot

**Comment by Auzgame** [comment]
> Just suggesting you could allow the users to adjust the strength of the bot
> 
> 
> 
> 

@Anonymous140041 On the greasy fork page it says you can change the strength of the bot (depth) by pressing the different keys on your keyboard. (Q-M = 1-26) with A being the the default
