### ISSUE TITLE
After 3 steps in the game against the man infinite loading and does not walk

### ISSUE THREAD

**Issue by Hasji** [Auzgame/userscripts#5]
Such a problem, I go into the game on the rating against a man set the auto move and to think I give 1 second, he makes 3-4 moves, then just hangs up and need to restart the engine, and so on to infinity. On the main account works fine and on the second works crookedly. Please fix it is not possible to play

**Comment by Auzgame** [comment]
> Such a problem, I go into the game on the rating against a man set the auto move and to think I give 1 second, he makes 3-4 moves, then just hangs up and need to restart the engine, and so on to infinity. On the main account works fine and on the second works crookedly. Please fix it is not possible to play

Can you tell me what browser your using? Can you also give me a copy of the console when the code bugs out? Also what depth did you have the bot set to?

**Comment by Hasji** [comment]
I use google chrome, in the file is a log of the game and restart the engine, here is the depth ``var lastValue = 10;``
[error.txt](https://github.com/Auzgame/userscripts/files/11308634/error.txt)

**Comment by Hasji** [comment]
Also found a bug that I play for black and it shows moves for white and draws squares on the table incorrectly

**Comment by Auzgame** [comment]
Currently, I am unable to reproduce the bug. Could you provide me with one more thing? Your Chess Board & Pieces settings. These often interfere with how the script grabs the chess information.

**Comment by Hasji** [comment]
Board and piece settings by mind

**Comment by Auzgame** [comment]
> Board and piece settings by mind

Can you please be more specific?

**Comment by Auzgame** [comment]
Closed due to inactivity
