### ISSUE TITLE
How do I delete it?

### ISSUE THREAD

**Issue by Burrito793** [Auzgame/userscripts#6]
How do I delete the chess bot?

**Comment by Auzgame** [comment]
[Tutorial](https://www.bing.com/search?pglt=41&q=How+do+I+delete+scripts+from+tampermonkey+because+i+dont+know+what+I%27m+doing&cvid=aa385067904d44678e6be4ef73d4ffc3&aqs=edge..69i57.16756j0j1&FORM=ANNTA1&PC=U531)
^^^
