### ISSUE TITLE
Auto Move feature does not work properly

### ISSUE THREAD

**Issue by Mon2903aZ** [Auzgame/userscripts#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Logs from your browser's developer tools console.

**Desktop (please complete the following information):**

**Additional context**

**Comment by Auzgame** [comment]
Hey @Mon2903aZ 
Could you please fill out the issue template provided and provide console logs so I can work on the issue.

**Comment by Auzgame** [comment]
I recently fixed the issue. Should now be working properly.
