### ISSUE TITLE
quit with the bot ads

### ISSUE THREAD

**Issue by OMT2011** [Auzgame/userscripts#9]
ads r retarded asf

**Comment by Auzgame** [comment]
@OMT2011 
Ads should only should once per loading the page. Basically it'll redirect you once then when you reopen the page there should be none. However if you reload the page it'll show one again. Tbh I think this way is flawed and I'll prob end up changing it

**Comment by Auzgame** [comment]
Just fixed the issue of ad spamming. Please update to the latest version

**Comment by OMT2011** [comment]
Welp, I have modded the code and deleted the ads. Feel free to keep em now. I will not resell or re advertise my code. it is only for personal use. Thank you! :)

**Comment by OMT2011** [comment]
It wasnt ad spamming, just disconnected from the game everytime an ad loaded

**Comment by OMT2011** [comment]
also, reason why you're greasy fork is being looked at by a mod?

**Comment by Auzgame** [comment]
> It wasnt ad spamming, just disconnected from the game everytime an ad loaded

Yeah, I don't mind the ad fix, really is not a big deal. Ads just give me more motivation to be working on this project

**Comment by Auzgame** [comment]
> also, reason why you're greasy fork is being looked at by a mod?

Reported due to "Checking for updates more then once per day"

**Comment by OMT2011** [comment]
ahh, you want the code for the "non ads mod" by me?

**Comment by Auzgame** [comment]
> > also, reason why you're greasy fork is being looked at by a mod?
> 
> Reported due to "Checking for updates more then once per day"

The "First Place guy" used to be second to me, till I stopped working on the script so I'm assuming its him

**Comment by OMT2011** [comment]
wow. thats cold

**Comment by Auzgame** [comment]
> ahh, you want the code for the "non ads mod" by me?

No thanks mate, I recently updated the code to use a timer. So it will only redirect for ads if a reload happens after 5 minutes

**Comment by OMT2011** [comment]
ok. Still gunna keep my version so i dont have ads. Sorry...

**Comment by OMT2011** [comment]
(at all)

**Comment by Auzgame** [comment]
> wow. thats cold

ikr, bros beefing with me. But tbh Idk how much longer I plan on working on this project. Im prob going to work on other cheats

**Comment by Auzgame** [comment]
> ok. Still gunna keep my version so i dont have ads. Sorry...

Doesn't bother me. Lots of people do it

**Comment by OMT2011** [comment]
What type of cheats? Tampermonkey intests me

**Comment by OMT2011** [comment]
if you have a discord i can add u?

**Comment by Auzgame** [comment]
> What type of cheats? Tampermonkey intests me

Idk, yet. I'm looking for good games that i can do

**Comment by OMT2011** [comment]
Hmm maybe like krunker?

**Comment by OMT2011** [comment]
maybe games outside of a webbrowser aswell?

**Comment by Auzgame** [comment]
> Hmm maybe like krunker?
I was looking into that but too many already exists

**Comment by OMT2011** [comment]
mk

**Comment by OMT2011** [comment]
fr tho, you got discord? I dont want to spam your comments xd

**Comment by Auzgame** [comment]
> fr tho, you got discord? I dont want to spam your comments xd

sure. Drop yours. I don't wont to drop mine for privacy reasons

**Comment by OMT2011** [comment]
Ok, its "exp0s3d" no numbers from new update

**Comment by hedihadi** [comment]
dude has made a script for free, deal with the ads.
